[tool.poetry]
name = "oracle.python.scripts"
version = "0.1.0"
description = ""
authors = ["jrdavison <jmsrdvsn@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
perfection = "^2.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
