import { Palette } from "./globals.slint";


export component Board inherits Rectangle {
    property <[int]> files: [1, 2, 3, 4, 5, 6, 7, 8];
    property <[string]> ranks: ["a", "b", "c", "d", "e", "f", "g", "h"];
    in property <[int]> board_state: [];

    for i in 64: Rectangle {
        height: parent.height / 8;
        width: parent.width / 8;

        // build the board (starting from the bottom left corner A1)
        x: mod(i, 8) * self.width;
        y: (7 - floor(i / 8)) * self.height;
        background: mod(floor(i / 8) + i, 2) == 0 ? #b58863 : #f0d9B5;

        // Add numbers to left file (1-8)
        if (mod(i, 8) == 0) : Text {
            text: files[floor(i / 8)]; // Adjust text to match reversed rank
            x: 3px;
            y: 0px;
            color: mod(floor(i / 8) + i, 2) == 0 ? Palette.light_sq : Palette.dark_sq;
            font-size: 16px;
            font-weight: 600;
        }

        // Add letters to bottom rank (a-h)
        if (i < 8) : Text {
            text: ranks[i];
            x: parent.width - 13px;
            y: parent.height - 22px;
            color: mod(floor(i / 8) + i, 2) == 0 ? #f0d9B5 : #b58863;
            font-size: 16px;
            font-weight: 600;
        }
    }
}
