import { VerticalBox, StandardTableView } from "std-widgets.slint";

import { Palette, Font } from "./globals.slint";
import { Dimensions } from "globals.slint";

export struct DashboardState {
    turn: int,
    halfmove_clock: int,
    fullmove_count: int,
    compute_time: string,
}

export component Dashboard inherits Rectangle {
    in property <int> turn: 0;  // 0 for white, 1 for black
    in property <int> fullmove_count: 0;
    in property <int> halfmove_clock: 0;
    in property <string> compute_time: "0.0";
    in property <percent> b_eval: 50%;
    in property <percent> w_eval: 50%;

    VerticalBox {
        Rectangle {
            height: 50px;
            width: 100%;
            background: turn == 0 ? white : black;
            border-radius: 5px;

            Text {
                text: (turn == 0 ? "White" : "Black") + " to move";
                color: turn == 0 ? black : white;
                horizontal-alignment: center;
                font-size: Font.font_size_lg;
                font-weight: Font.bold;
            }
        }
    }
    StandardTableView {
        x: 0;
        height: 147px;
        y: Dimensions.board_size - 147px;
        width: 100%;
        rows: [
            [
                { text: "Fullmove Count:" }, { text: fullmove_count },
            ],
            [
                { text: "Halfmove Clock:" }, { text: halfmove_clock },
            ],
            [
                { text: "Time to compute valid moves:" }, { text: compute_time },
            ]
        ];
    }
}
