import { VerticalBox, StandardTableView } from "std-widgets.slint";

import { Palette, Font } from "./globals.slint";
import { Dimensions } from "globals.slint";

export struct DashboardState {
    turn: int,
    en_passant_square: string,
    halfmove_clock: int,
    fullmove_count: int,
    compute_time: string,
}

export component Dashboard inherits Rectangle {
    in property <DashboardState> dashboard_state;
    in property <percent> b_eval: 50%;
    in property <percent> w_eval: 50%;

    VerticalBox {
        padding-bottom: 0px;
        Rectangle {
            height: 50px;
            width: 100%;
            background: dashboard_state.turn == 0 ? white : black;
            border-radius: 5px;

            Text {
                text: (dashboard_state.turn == 0 ? "White" : "Black") + " to move";
                color: dashboard_state.turn == 0 ? black : white;
                horizontal-alignment: center;
                font-size: Font.font_size_lg;
                font-weight: Font.bold;
            }
        }
    }
    StandardTableView {
        x: 0;
        height: 182px;
        y: Dimensions.board_size - 182px;
        width: 100%;
        rows: [
            [
                { text: "Fullmove Count:" }, { text: dashboard_state.fullmove_count },
            ],
            [
                { text: "Halfmove Clock:" }, { text: dashboard_state.halfmove_clock },
            ],
            [
                { text: "En Passant Square:" }, { text: dashboard_state.en_passant_square },
            ],
            [
                { text: "Time to compute valid moves:" }, { text: dashboard_state.compute_time },
            ]
        ];
    }
}
